### ISSUE TITLE
Prior Preservation loss error

### ISSUE THREAD

**Issue by wcarletsdrive** [ShivamShrirao/diffusers#103]
### Describe the bug

RuntimeError: CUDA error: unknown error CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

That is the error I get when I run prior preservation loss, but without it everything is running fine. I saw someone have a similar issue except for the cuda error, it doesn't say anything about running out of memory and I used the command nvidia-smi to see if any processes are running on my gpu and it said 0. So what's going on? I have 12GB Vram.

It will start with generating class images: 0/1 then give me the error above.

### System Info

Windows 10 21H2, Linux WSL latest version

**Comment by kjerk** [comment]
If you have `--train_text_encoder` and `--gradient_accumulation_steps` both enabled then try disabling `--gradient_accumulation_steps`. This was marked as unsupported on the diffusers parent repo and if I recall that fixed this for me previously.

**Comment by ZeroCool22** [comment]
> `--train_text_encoder`

What does `--train_text_encoder `?

**Comment by kjerk** [comment]
See: [https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README.md](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README.md#:~:text=800%20%5C%0A%20%20%2D%2Dmixed_precision%3Dfp16-,Fine%2Dtune%20text%20encoder%20with%20the%20UNet,-.)

> Fine-tune text encoder with the UNet.
The script also allows to fine-tune the text_encoder along with the unet. It's been observed experimentally that fine-tuning text_encoder gives much better results especially on faces. Pass the --train_text_encoder argument to the script to enable training text_encoder.
Note: Training text encoder requires more memory, with this option the training won't fit on 16GB GPU. It needs at least 24GB VRAM.
