### ISSUE TITLE
OutOfMemoryError on an RTX 2080 TI

### ISSUE THREAD

**Issue by RobinFrcd** [ShivamShrirao/diffusers#108]
Hi,
I'm trying to make `dreambooth` work on my 2080 TI. I've compiled xformers with `TORCH_CUDA_ARCH_LIST=7.5`. 

My GPU has about 10.5 GiB of available VRAM. However, when I run the training on my dataset, I get `torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 10.74 GiB total capacity; 8.94 GiB already allocated; 9.31 MiB free; 9.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.`

I've tried to change `--resolution=512` to `--resolution=256` but it didn't help.

```
accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of sks person" \
  --class_prompt="a photo of person" \
  --resolution=256 \
  --train_batch_size=1 \
  --sample_batch_size=1 \
  --gradient_accumulation_steps=1 --gradient_checkpointing \
  --learning_rate=2e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=800 \
  --mixed_precision=fp16 \
  --use_8bit_adam
```

Am I missing something here ? I thought it could run with [9.92 GiB](https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth).

Thanks !

**Comment by ShivamShrirao** [comment]
How did u install diffusers ?

**Comment by RobinFrcd** [comment]
```
pip install git+https://github.com/ShivamShrirao/diffusers.git
pip install -U -r requirements.txt
```

**Comment by ShivamShrirao** [comment]
Can u verify xformers is working ?

**Comment by RobinFrcd** [comment]
Sure, is there a way to verify this easily ?

**Comment by ShivamShrirao** [comment]
Try with just `import xformers`

**Comment by RobinFrcd** [comment]
Oh yes, sure, it works fine !

**Comment by blackmagic24** [comment]
The same here.
It does not work natively under Linux. (Ubuntu or Fedora)

diffusers install:
pip install git+https://github.com/ShivamShrirao/diffusers.git
pip install -U -r requirements.txt

xformers self compiled with cuda 11.6
conda install -c "nvidia/label/cuda-11.6.2" cuda

or from here: 
conda install -y -c pytorch -c conda-forge cudatoolkit=11.6 pytorch=1.12.1
conda install -y xformers -c xformers/label/dev

nothing works:

RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 9.78 GiB total capacity; 8.06 GiB already allocated; 15.31 MiB free; 8.15 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   38C    P8    29W / 320W |      0MiB / 10240MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```
The really strange thing is that it runs under Windows 11 WSL (ubuntu) without any problems.
The same launch.sh script and conda environment.

WSL installation guide from here: https://pastebin.com/uE1WcSxD
I would rather run it on Linux.

**Comment by RobinFrcd** [comment]
I've seen that PyTorch is not compatible with `CUDA 11.8`, maybe that's your issue here ?

**Comment by blackmagic24** [comment]
> I've seen that PyTorch is not compatible with `CUDA 11.8`, maybe that's your issue here ?

conda list cudatoolkit
```
# Name                    Version                   Build  Channel
cudatoolkit               11.6.0              hecad31d_10    conda-forge
```

**Comment by blackmagic24** [comment]
I tried around a bit, now it works for me:
```
conda create --name diffusers-cuda116 python=3.9
conda activate diffusers-cuda116
conda install -c "nvidia/label/cuda-11.6.2" cuda
conda install gcc=11.3.0 cxx-compiler -c conda-forge
conda install -y -c pytorch -c conda-forge pytorch=1.12.1 torchvision torchaudio

# RTX30XX
export FORCE_CUDA="1"
export TORCH_CUDA_ARCH_LIST=8.6
export CUDA_VISIBLE_DEVICES=0 
pip install git+https://github.com/facebookresearch/xformers@1d31a3a#egg=xformers

git clone https://github.com/ShivamShrirao/diffusers.git
cd diffusers
pip install .
cd examples/dreambooth
pip install -r requirements.txt
pip install -U --pre triton
pip install ninja bitsandbytes
```

**Comment by RobinFrcd** [comment]
Very similar to what I've done, I'll give it another try, maybe there's an issue with my environment with all the tries I've done !

**Comment by ZeroCool22** [comment]
> Try with just `import xformers`

![Screenshot_2](https://user-images.githubusercontent.com/13344308/199876869-fb4b2de6-df66-4d7b-91e3-e17cd29b6564.jpg)

When i try import.

**Comment by RobinFrcd** [comment]
`import xformers` should be done in the python interpreter. `python -c "import xformers"`

**Comment by ZeroCool22** [comment]
> `import xformers` should be done in the python interpreter. `python -c "import xformers"`

![Screenshot_3](https://user-images.githubusercontent.com/13344308/199966964-4c3894d3-f6ea-4818-89a7-4c3d4fa4ad48.jpg)

I do it in **Ubuntu console**, because i use with **WSL2**.
