### ISSUE TITLE
Different output on local machine gpu 3060

### ISSUE THREAD

**Issue by AhmedAbdellaa** [ShivamShrirao/diffusers#194]
### Describe the bug

When I train the notebook on colab it output good result similar to the images I trained on
But when I trained it on my local machine with GPU Nvidia 3060 it produce a very bad results not similar at all to the image although I installed all libraries as same as to colab but I don't know why the result is different

### System Info

diffusers' version: 0.11.1
Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.29
Python version: 3.8.10
PyTorch version (GPU?): 1.13.1+cu116 (True)
Huggingface_ hub version: 0.11.1
Transformers version: 4.25.1
Using GPU in script?: nvidia rtx 3060
Using distributed or parallel set-up in script?: no

**Comment by raphaelmerx** [comment]
Likely the issue is that the xformers library installed by the notebook is compiled for T4 and A100 GPUs, not for a 3060: https://github.com/brian6091/xformers-wheels/releases/tag/0.0.15.dev0%2B4c06c79

Try without using xformers. You might run out of memory, in which case you might want to remove `--train_text_encoder`

**Comment by timtaotao** [comment]
same, colab is fine, I can get good results, but when I shift to local machine with WSL, the results are bad and seems the trainning is not working at all. when I output the intermediate results, every time I get the same pictures. Do you have any idea how to resolve that?

**Comment by timtaotao** [comment]
The problem is with xformers, by following #[631](https://github.com/facebookresearch/xformers/issues/631) updating the xformers solves my problem

**Comment by raphaelmerx** [comment]
Now that fb released [xformers 0.0.16](https://github.com/facebookresearch/xformers/releases/tag/v0.0.16), they are available as wheels on Pypi, so can you try `pip install -U xformers`

**Comment by AhmedAbdellaa** [comment]
Thanks a lot, it works fine now after updating xformer but its maximum train resolution is 265 with my 12GB vram RTX 3060

**Comment by timtaotao** [comment]
should work with 512, I'm using rtx 3060 as well, did you follow the colab notebook?

**Comment by AhmedAbdellaa** [comment]
Yes same as notebook but gpu run out of memory
